use LigaFotbal

CREATE TABLE Echipa(
	idEchipa INT PRIMARY KEY IDENTITY(1,1),
	idSerie INT,
	numeEchipa VARCHAR(50) DEFAULT ''

	CONSTRAINT FK_ECHIPA_SERIE FOREIGN KEY (idSerie) REFERENCES Serie ON DELETE CASCADE ON UPDATE NO ACTION

)