use LigaFotbal

CREATE TABLE Federatie(
	idFederatie INT IDENTITY(1,1) PRIMARY KEY , 
	idTara INT UNIQUE,
	nume VARCHAR(50)

	CONSTRAINT FK_FEDERATIE_TARA FOREIGN KEY (idTara) REFERENCES Tara ON DELETE CASCADE ON UPDATE NO ACTION

)