use LigaFotbal

CREATE TABLE Echipa_Fan(
	idEchipa INT,
	idFan INT,
	fanClub VARCHAR(50),

	CONSTRAINT FK_ECHIPA_FAN_ECHIPA FOREIGN KEY (idEchipa) REFERENCES Echipa,
	CONSTRAINT FK_ECHIPA_FAN_FAN FOREIGN KEY (idFan) REFERENCES Fan,
	CONSTRAINT PK_ECHIPA_FAN PRIMARY KEY (idEchipa,idFan),

)