use LigaFotbal

CREATE TABLE Manager(
	idManager INT PRIMARY KEY IDENTITY(1,1),
	idEchipa INT FOREIGN KEY REFERENCES Echipa,
	nume VARCHAR(50),

	CONSTRAINT FK_MANAGER_ECHIPA FOREIGN KEY (idEchipa) REFERENCES Echipa ON DELETE CASCADE ON UPDATE NO ACTION,


)