use LigaFotbal

CREATE TABLE Jucator(
	idJucator INT PRIMARY KEY IDENTITY(1,1),
	idEchipa INT FOREIGN KEY REFERENCES Echipa,
	nume VARCHAR(50) DEFAULT '' ,
	prenume VARCHAR(50) DEFAULT '',

	CONSTRAINT FK_JUCATOR_ECHIPA FOREIGN KEY (idEchipa) REFERENCES Echipa ON DELETE CASCADE ON UPDATE NO ACTION,

)