CREATE TABLE ComisieArbitri(
	idComisie INT PRIMARY KEY IDENTITY(1,1),
	idFederatie INT ,
	numeComisie VARCHAR(50) 

	CONSTRAINT FK_COMISIEARBITRII_FEDERATIE FOREIGN KEY (idFederatie) REFERENCES Federatie ON DELETE CASCADE ON UPDATE NO ACTION
)