USE LigaFotbal
GO 
DROP TABLE Campionat_Echipa;
CREATE TABLE Campionat_Echipa(
	idEchipa INT,
	idCampionat INT,
	anCampionat INT NOT NULL,
	puncte INT,

	CONSTRAINT FK_CAMPIONAT_ECHIPA_ECHIPA FOREIGN KEY (idEchipa) REFERENCES Echipa ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_CAMPIONAT_ECHIPA_CAMPIONAT FOREIGN KEY (idCampionat) REFERENCES Campionat ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT PK_CAMPIONAT_ECHIPA PRIMARY KEY(idEchipa, idCampionat,anCampionat) 
)