use LigaFotbal

CREATE TABLE Echipa_Sponsor(
	idEchipa INT,
	idSponsor INT,
	beneficiu VARCHAR(50),
	suma FLOAT,
	CHECK (suma >= 0),

	CONSTRAINT FK_ECHIPA_SPONSOR_ECHIPA FOREIGN KEY (idEchipa) REFERENCES Echipa ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_ECHIPA_SPONSOR_SPONSOR FOREIGN KEY (idSponsor) REFERENCES Sponsor ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT PK_ECHIPA_SPONSOR PRIMARY KEY(idEchipa,idSponsor)
	
)