
use LigaFotbalTest
GO

IF(OBJECT_ID(N'uspResetConstraints',N'P') IS NOT NULL)
	DROP PROC uspResetConstraints
GO
CREATE PROC uspResetConstraints
AS
BEGIN
	
	IF( OBJECT_ID(N'FK_ECHIPA_SPONSOR_SPONSOR') IS NULL)
	BEGIN
		ALTER TABLE Echipa_Sponsor
		ADD CONSTRAINT FK_ECHIPA_SPONSOR_SPONSOR
		FOREIGN KEY (idSponsor)
		REFERENCES Sponsor(idSponsor)
	END

	IF( OBJECT_ID(N'FK_ECHIPA_SPONSOR_ECHIPA') IS NULL)
	BEGIN
		ALTER TABLE Echipa_Sponsor
		ADD CONSTRAINT FK_ECHIPA_SPONSOR_ECHIPA
		FOREIGN KEY (idEchipa)
		REFERENCES Echipa(idEchipa)
	END



	IF( OBJECT_ID(N'PK_ECHIPA_SPONSOR') IS NULL)
	BEGIN
		ALTER TABLE Echipa_Sponsor
		ADD CONSTRAINT PK_ECHIPA_SPONSOR
		PRIMARY KEY (idEchipa,idSponsor)
	END

	
	IF ( OBJECT_ID(N'PK_ECHIPA_CAMPIONAT') IS NULL)
	BEGIN
		ALTER TABLE Campionat_Echipa
		ADD CONSTRAINT PK_ECHIPA_CAMPIONAT
		PRIMARY KEY (idEchipa,idCampionat,anCampionat)
	END

	IF(OBJECT_ID(N'FK_CAMPIONAT_ECHIPA_ECHIPA') IS NULL)
	BEGIN
		ALTER TABLE Campionat_Echipa
		ADD CONSTRAINT FK_CAMPIONAT_ECHIPA_ECHIPA
		FOREIGN KEY (idEchipa)
		REFERENCES Echipa
	END

	IF(OBJECT_ID(N'FK_CAMPIONAT_ECHIPA_CAMPIONAT') IS NULL)
	BEGIN
		ALTER TABLE Campionat_Echipa
		ADD CONSTRAINT FK_CAMPIONAT_ECHIPA_CAMPIONAT
		FOREIGN KEY (idCampionat)
		REFERENCES Campionat(idCampionat)
	END

	IF(OBJECT_ID(N'PK_ECHIPA_FAN') IS NULL)
	BEGIN
		ALTER TABLE Echipa_Fan
		ADD CONSTRAINT PK_ECHIPA_FAN
		PRIMARY KEY (idEchipa,idFan)
	END

	IF(OBJECT_ID(N'FK_ECHIPA_FAN_ECHIPA') IS NULL)
	BEGIN
		ALTER TABLE Echipa_Fan
		ADD CONSTRAINT FK_ECHIPA_FAN_ECHIPA
		FOREIGN KEY (idechipa)
		REFERENCES Echipa(idEchipa)
	END
	
	IF(OBJECT_ID(N'FK_ECHIPA_FAN_FAN')IS NULL)
	BEGIN
		ALTER TABLE Echipa_Fan
		ADD CONSTRAINT FK_ECHIPA_FAN_FAN
		FOREIGN KEY (idFan)
		REFERENCES Fan(idFan)
	END
	

	IF(OBJECT_ID(N'PK_SERIE') IS NULL)
	BEGIN	
		ALTER TABLE Serie
		ADD CONSTRAINT PK_SERIE
		PRIMARY KEY (idSerie)
	END

	 
END

